### ISSUE TITLE
Falha de Segurança nos Logs

### ISSUE THREAD

**Issue by fabiofeichtinger** [claudiosmweb/woocommerce-mundipagg#5]
Quando os logs são ativados o mesmo registra o número de cartão de crédito que foi passado para a MundiPagg sem nenhuma ocultação de dígitos.

**Comment by claudiosanches** [comment]
Log é para usar em ambiente de desenvolvimento com dados de testes.
Se estiver usando qualquer tipo de log aberto em um ambiente de produção, com certeza é uma falha de segurança, contendo ou não dados de cartão.

**Comment by fabiofeichtinger** [comment]
Entendo seu ponto Claudio, mas a ideia de manter o log habilitado em ambientes de processamento de cartão de crédito permite que eu veja qual foi a resposta do gateway para uma transação de produção específica, podendo dar mais detalhes ao cliente e potencialmente recuperar uma venda.

**Comment by claudiosanches** [comment]
Log é para depuração, se quer mais detalhes, da para habilitar no plugin, mas usar o log para isso é errado.
Se quer mudar isso, sinta-se livre para enviar um Pull Request.
